/**
 * Reads .env and writes src/environment/environment.generated.ts.
 * Run before serve/build so private API_BASE is used. .env is gitignored.
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const envPath = path.join(root, '.env');
const generatedPath = path.join(root, 'src/environment/environment.generated.ts');
const basePath = path.join(root, 'src/environment/environment.base.ts');

function parseEnv(content) {
  const out = {};
  content.split('\n').forEach((line) => {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (m) out[m[1].trim()] = m[2].trim().replace(/^["']|["']$/g, '');
  });
  return out;
}

let apiBase = 'http://localhost:8080/api';
let version = 'v4.20.0.0';
let versionBD = '4.20.0.0';
let testing = true;
let production = false;

if (fs.existsSync(envPath)) {
  const env = parseEnv(fs.readFileSync(envPath, 'utf8'));
  if (env.API_BASE) apiBase = env.API_BASE;
  if (env.VERSION) version = env.VERSION;
  if (env.VERSION_BD) versionBD = env.VERSION_BD;
  if (env.TESTING !== undefined) testing = env.TESTING === 'true';
  if (env.PRODUCTION !== undefined) production = env.PRODUCTION === 'true';
} else {
  // Fallback: use base file values so app works without .env
  if (fs.existsSync(basePath)) {
    const base = fs.readFileSync(basePath, 'utf8');
    const m = base.match(/BASE:\s*['"]([^'"]*)['"]/);
    if (m && m[1]) apiBase = m[1];
  }
}

const content = `// Generated by scripts/load-env.js from .env — do not edit
export const environment = {
  version: '${version}',
  versionBD: '${versionBD}',
  API: {
    BASE: '${apiBase.replace(/'/g, "\\'")}',
  },
  TESTING: ${testing},
  production: ${production},
};
`;

fs.mkdirSync(path.dirname(generatedPath), { recursive: true });
fs.writeFileSync(generatedPath, content, 'utf8');
console.log('Environment generated from .env (API_BASE used)');
console.log('Generated:', generatedPath);
